### ISSUE TITLE
Results Page

### ISSUE THREAD

**Issue by baokhoavu** [friends4eva/Food-meets-tinder#5]
Displays Liked Choices for that Session

**Comment by yeahbq** [comment]
![img_3731](https://cloud.githubusercontent.com/assets/23482726/22717175/69a8bf6e-ed4e-11e6-838f-f1e4a1a61ae3.JPG)

**Comment by yeahbq** [comment]
![img_1558](https://cloud.githubusercontent.com/assets/23482726/22811882/64633710-eef6-11e6-99ac-f9387c5327ef.JPG)
![img_7161](https://cloud.githubusercontent.com/assets/23482726/22811883/6464290e-eef6-11e6-94b5-c4b0d07ca050.JPG)

**Comment by yeahbq** [comment]
Filter list from req.sessions.businesses[i] for if .likes is greater than zero.  OR just use an IF statement and attempt to render all of the businesses. IF likes is greater than 0, then render it in the liked page!!!!!
