### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by baokhoavu** [friends4eva/Food-meets-tinder#7]
Likes .. counter=0++
Dislikes .. counter=0++
Super Like
Super Dislike

**Comment by yeahbq** [comment]
![img_8519](https://cloud.githubusercontent.com/assets/23482726/22717139/3e2b1e54-ed4e-11e6-97ab-77bfa52eb08b.JPG)

**Comment by yeahbq** [comment]
As of last commit to github, likes and dislikes are saved to req.sessions.businesses[number].likes and req.sessions.businesses[number].dislikes!!!

Last step for CRUD is find and update entry in mongoose
